######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 4 13:03:52 2011
######################################################################

TEMPLATE = app
TARGET = zappy-tester
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += controller.hxx
FORMS += zappytester.ui
SOURCES += controller.cxx main.cxx
